name: dartlang_strong
description: dartlang.org strong mode examples

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  test: ^1.0.0
  pedantic: ^1.0.0
  dartlang_examples_util:
    path: ../util
