name: dartlang_strong
description: dartlang.org strong mode examples
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  test: ^0.12.30
  dartlang_examples_util:
    path: ../util
