name: examples_strong
description: dart.dev strong mode examples

environment:
  sdk: '>=2.3.1 <3.0.0'

dev_dependencies:
  examples_util: {path: ../util}
  pedantic: ^1.0.0
  test: ^1.0.0

dependency_overrides:
  analyzer: 0.39.1
