name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
version: 0.2.0-dev
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/sdk_builds.dart
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  googleapis: ^0.53.0
  http: ^0.12.0+2
  path: ^1.6.2
  pub_semver: ^1.4.2
  quiver: ^2.0.3
dev_dependencies:
  test: ^1.6.0
