name: effective_dart_rules
version: 0.0.1
description: Builds a file with all the rules in the different sections of Effective Dart.
dependencies:
  html_unescape: ^0.1.4
  markdown: ^0.10.1
  path: ^1.3.9
