# Set update schedule for GitHub Actions
# See https://docs.github.com/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "auto.dependencies"
      - "auto.github-action"
      - "lang.yaml"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    labels:
      - "auto.dependencies"
      - "auto.npm"
      - "lang.javascript"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "auto.dependencies"
      - "auto.submodules"
