# Set update schedule for GitHub Actions
# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infra.dependencies"
      - "infra.bundler"
      - "lang.ruby"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infra.dependencies"
      - "infra.docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infra.dependencies"
      - "infra.github-action"
      - "lang.yaml"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    labels:
      - "infra.dependencies"
      - "infra.npm"
      - "lang.javascript"
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "infra.dependencies"
      - "infra.submodules"
