#!/bin/bash

REQUIRED_DART_VERSION="3.8"

# Check that the 'dart' command is available on the user's path.
if ! command -v dart &> /dev/null; then
  echo "Dart not found. To learn how to setup Dart, follow the instructions at https://dart.dev/get-dart."
  exit 1
fi

# Check that the current version of a tool is the same or
# newer than a required version.
version_is_new_enough() {
  required_version="$1"
  current_version="$2"

  # Split the version strings into lists based on the dot separators.
  IFS='.' read -ra required_list <<< "$required_version"
  IFS='.' read -ra current_list <<< "$current_version"

  # Compare each portion of the version number.
  for ((i = 0; i < ${#required_list[@]}; i += 1)); do
    required_segment="${required_list[i]:-0}"
    current_segment="${current_list[i]:-0}"

    if [[ "$required_segment" -gt "$current_segment" ]]; then
      # The current version is too low.
      return 0
    elif [[ "$required_segment" -lt "$current_segment" ]]; then
      # The current version is higher, which is ok.
      return 1
    fi
  done

  # The current version is (mostly) the same as the required version.
  return 1
}


# Determine the available Dart SDK version.
dart_version=$(dart --version | grep -oE 'Dart SDK version: [0-9.]+' | cut -d ' ' -f 4)

# Validate the version of the installed Dart SDK.
if version_is_new_enough "$REQUIRED_DART_VERSION" "$dart_version"; then
  echo "Dart version $dart_version is too low. Version $REQUIRED_DART_VERSION or later is required."
  exit 1
fi

# Verify that Dart dependencies have been retrieved.
if [[ ! -d ".dart_tool" ]]; then
  dart pub get
fi

# Run the Dart site tool and pass through all arguments.
dart run dart_site "$@"
