source "http://rubygems.org"
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-assets', '2.1.2'
gem 'jekyll-sitemap'
gem 'jekyll-toc'
gem 'kramdown'
gem 'nokogiri'
gem 'sass'
gem 'uglifier'
