name: null_safety_codelab
description: dart.dev example code for null safety codelab

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  examples_util: {path: ../util}
  pedantic: ^1.11.0
  test: ^1.17.1
