# See https://github.com/dart-lang/build/tree/master/build_web_compilers#configuration
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          compilers:
            dart2js:
              args:
                - --dump-info
                - --no-frequency-based-minification
                - --no-source-maps
                - --show-package-warnings
                - -O4
            dart2wasm:
              args:
                - -O2
