builders:
  stylesHashBuilder:
    import: 'package:dart_dev_site/builders.dart'
    builder_factories: [ 'stylesHashBuilder' ]
    build_extensions:
      "web/assets/css/main.css":
        - "lib/src/style_hash.dart"
    auto_apply: root_package
    build_to: source

targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        dev_options:
          compilers:
            dartdevc:
        release_options:
          # Use production compilers for release builds, and ensure
          # kReleaseMode in jaspr is enabled.
          compilers:
            dart2js:
              args: [-O4, -Djaspr.flags.release=true]
            dart2wasm:
              args: [-O4, -Djaspr.flags.release=true]
