name: create_libraries
description: dart.dev example code.
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  analyzer: 0.39.1
