name: effective_dart_rules
description: >
  Builds a file with all the rules in the different sections of Effective Dart.
version: 0.0.4
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  html_unescape: ^2.0.0
  markdown: ^7.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
