name: effective_dart_rules
description: >
  Builds a file with all the rules in the different sections of Effective Dart.
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  html_unescape: ^2.0.0
  markdown: ^7.1.1
  path: ^1.8.3

dev_dependencies:
  analysis_defaults:
    path: ../../site-shared/packages/analysis_defaults
