name: Page issue
description: Help improve the content or quality of a dart.dev page.
labels: [from.page-issue]
body:
  - type: markdown
    attributes:
      value: |
          Found a typo? You can fix it yourself!

          1. Scroll to the bottom of the page with the typo.
          1. Use the "View source" link located after the content to navigate to the page's source on GitHub.
          1. Fix the typo.
          1. Click **Commit changes...**.
          1. Update the title, add a commit message, and add a description.
          1. Click **Propose changes**.

          If you want another contributor to fix this issue, complete this form.
  - type: input
    id: page-url
    attributes:
      label: Page URL
      placeholder: "Add the address of this page. An example would be https://dart.dev/language"
    validations:
      required: true
  - type: input
    id: page-source
    attributes:
      label: Page source
      placeholder: The bug link provides this information.
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      placeholder: Provide a clear and concise description of you believe to be in error.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Expected fix
      placeholder: Provide a clear and concise description of how you think this problem should be fixed.
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      placeholder: |
        Provide anything else that should be known about the problem. 
        This could include:

        * when in your workflow this occurred
        * what platform and browser you are using
        * other configuration or circumstantial information that you think could impact fixing your issue
    validations:
      required: false
  - type: checkboxes
    id: volunteer
    attributes:
      label: I would like to fix this problem.
      description: Let us know if you want to try fixing this yourself.
      options:
        - label: I will try and fix this problem on dart.dev.
          required: false
