name: Topic request
description: What information should be on dart.dev but isn't covered well (or at all)?
labels: [co.request, from.user]
body:
  - type: textarea
    id: problem
    attributes:
      label: What information needs to be added?
      placeholder: Provide a clear and concise description of what you expected to find on dart.dev, but didn't.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Where should this new content appear?
      placeholder: Let us know where you'd expect to see this new information.
    validations:
      required: false
  - type: checkboxes
    id: volunteer
    attributes:
      label: I would like to fix this problem.
      description: Let us know if you want to try fixing this yourself.
      options:
        - label: I will try and fix this problem on dart.dev.
          required: false
