name: fetch_data_example
description: Fetch data example
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.1
  test: ^1.17.0
