# See https://github.com/dart-lang/build/tree/master/build_web_compilers#configuration
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          dart2js_args:
            - --dump-info
            - --no-frequency-based-minification
            - --no-source-maps
            - --show-package-warnings
            - -O4
