name: dartpad_picker
publish_to: none

environment:
  sdk: ^3.3.0

dev_dependencies:
  analysis_defaults:
    path: ../../site-shared/packages/analysis_defaults
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
