name: dash_site
description: Dart-based tools for building dart.dev.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.13.0

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  excerpter:
    git:
      url: https://github.com/flutter/website
      path: packages/excerpter
      ref: 74b7c5c06ebe9bf8c3e007e120a71144af5eb175
  fbh_front_matter: ^0.0.1
  html_unescape: ^2.0.0
  http: ^1.6.0
  intl: ^0.20.3
  io: ^1.1.0
  linkcheck: ^3.1.0
  markdown: ^7.3.1
  path: ^1.9.1
  pub_semver: ^2.2.0
  yaml: ^3.1.4
  yaml_variable_scanner: ^0.1.0

dev_dependencies:
  analysis_defaults:
    git:
      url: https://github.com/flutter/website
      path: packages/analysis_defaults
      ref: 74b7c5c06ebe9bf8c3e007e120a71144af5eb175
