exclude:
  # These are copied from the main _config.yml.
  - appengine
  - tests
  - site
  # These speed up the build when all you worry about is the frontpage.
  - _articles
  - _tutorials
  - _guides/language
  - _guides/libraries
  - tools
  - install
  - resources