name: download_archive
description: Display a list of downloads for www.dartlang.org.
dependencies:
  pub_semver: ^1.3.2
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
