name: download_archive
description: Display a list of downloads for dart.dev.
dependencies:
  pedantic: ^1.7.0
  dart_sdk_archive:
    path: ../dart_sdk_archive
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
