name: download_archive
description: Display a list of downloads for dart.dev.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dart_sdk_archive:
    path: ../dart_sdk_archive
dev_dependencies:
  build_runner: ^1.12.0
  pedantic: ^1.11.0
  build_web_compilers: ^2.16.0
