name: dart_sdk_archive
description: An absolute bare-bones web app.
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  http: ^0.12.0
  path: ^1.6.2
  quiver: ^2.0.0
  platform_detect: ^1.3.5
  sdk_builds:
    path: ../sdk_builds.dart

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  dart_style: ^1.2.0
  grinder: ^0.8.0
  pedantic: ^1.0.0
  test: ^1.6.0
