#!/usr/bin/env dart

import 'dart:io';
import 'dart:async';

import 'youtube.dart' as youtube;

final String PLAYLIST_ID = 'PLndbWGuLoHeaPgfKYlwJvDDxCrRdDbga3';

final String OUTPUT_FILENAME = 'src/site/dart-tips/episodes.yaml';

writePlaylistYaml(Directory directory, Map playlist) {
  var file = new File('${directory.path}/../$OUTPUT_FILENAME');
  IOSink output = file.openWrite();
  output.write("""
# DO NOT EDIT THIS FILE - IT IS AUTOGENERATED
# See scripts/gen_dartisans_playlist.dart
episodes:
""");
  var entries = playlist['feed']['entry'];
  for (var i = 0; i < entries.length; i++) {
    var epNum = i + 1;
    writeEntry(output, entries[i], epNum);
  }
  output.close();
}

writeEntry(IOSink out, Map entry, int epNum) {
  String playerUrl = entry[r'media$group'][r'media$player'][0]['url'];
  String youtubeId = new RegExp("v=(.*)&").firstMatch(playerUrl)[1];
  String title = entry['title'][r'$t'];
  String subtitle;
  Match match = new RegExp(r"(.*) -").firstMatch(title);
  if (match == null) {
    print("Title '$title' does not have a -");
    return;
  } else {
    subtitle = match[1];
  }
  String thumbnail = entry[r'media$group'][r'media$thumbnail'][0]['url'].replaceFirst('http:', '');
  String recorded;
  if (entry[r'yt$recorded'] == null) {
    print("No explicit recorded date for $title. Please set.");
    return;
  } else {
    recorded = entry[r'yt$recorded'][r'$t'];
  }
  String desc = entry['content'][r'$t']
                  .replaceAll("\n", ' ')
                  .replaceAll('"', "'");

  var salesPitch = desc.indexOf("Interested in Dart training");
  if (salesPitch < 0) {
    print("WARNING No salespitch for $title ($desc). What should I do?");
    return;
  } else {
    desc = desc.substring(0, salesPitch);
  }

  out.write("""
- title: "${title}"
  subtitle: "${subtitle}"
  pubdate: ${recorded}
  description: "${desc}"
  num: $epNum
  youtubeid: $youtubeId
  thumbnail: $thumbnail
""");
}

main() {
  var script = new File(new Options().script);
  var directory = script.directorySync();

  youtube.fetchPlaylist(PLAYLIST_ID)
  .then((Map data) {
    writePlaylistYaml(directory, data);
    print("Complete!");
  });
}