# This follow defines various global variables to use throughout the site.
# You can access them using Liquid like: `{{site.dart-api}}`.

title: Dart
description: >-
  Dart is a client-optimized language for developing fast apps on any platform.
url: https://dart.dev
repo:
  this: https://github.com/dart-lang/site-www
  shared: https://github.com/dart-lang/site-shared
  dart:
    org: https://github.com/dart-lang
    sdk: https://github.com/dart-lang/sdk
    lang: https://github.com/dart-lang/language
branch: main

flutter: https://flutter.dev
flutter-docs: https://docs.flutter.dev
dart-api: https://api.dart.dev
flutter-api: https://api.flutter.dev
pub: https://pub.dev
pub-api: https://pub.dev/documentation
pub-pkg: https://pub.dev/packages
dartpad: https://dartpad.dev
news: https://news.dartlang.org
announce: https://groups.google.com/a/dartlang.org/g/announce
android-dev: https://developer.android.com
apple-dev: https://developer.apple.com

show_banner: true

# Increment this global og:image URL version number (used as a query parameter)
# when you update any og:image file. (Also increment the corresponding number
# in the `firebase.json` redirect rule.)
og_image_vers: "?2"

sdkInfo:
  channel: stable
  version: 3.3.2
