name: dart_tools
description: Dart-based tools for site-www.
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  path: ^1.8.3

dev_dependencies:
  analysis_defaults:
    path: ../../site-shared/packages/analysis_defaults
