name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  googleapis: ^11.4.0
  http: ^1.1.0
  path: ^1.8.3
  pub_semver: ^2.1.4

dev_dependencies:
  analysis_defaults:
    path: ../../../site-shared/packages/analysis_defaults
  test: ^1.24.6
