name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
publish_to: none

environment:
  sdk: ^2.19.4

dependencies:
  googleapis: ^10.1.0
  http: ^0.13.5
  path: ^1.8.3
  pub_semver: ^2.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
