name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  googleapis: ^12.0.0
  http: ^1.1.2
  path: ^1.9.0
  pub_semver: ^2.1.4

dev_dependencies:
  analysis_defaults:
    path: ../../../site-shared/packages/analysis_defaults
  test: ^1.25.0
