name: homepage_jw
version: 0.0.1
description: First example at the top of the new homepage

gist: https://gist.github.com/kwalrath/a6907e26b96678b75303
dartpad: https://dartpad.dartlang.org/a6907e26b96678b75303
