name: examples_util
description: dart.dev example utilities.
version: 0.0.2

environment:
  sdk: '>=2.3.1 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

dependency_overrides:
  analyzer: 0.39.1
