name: httpserver
description: A sample application

homepage: https://www.dartlang.org/docs/tutorials/httpserver/

dependencies:
  http_server: ^0.9.2

dev_dependencies:
  test: ^0.12.0
  dartlang_examples_util:
    path: ../util
