name: httpserver
description: Sample HTTP clients and servers
homepage: https://dart.dev/tutorials/server/httpserver

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  http_server: ^0.9.6

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  test: ^1.0.0
  pedantic: ^1.0.0
